#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#feh --bg-fill ~/downloads/final.png &
~/.scripts/setwal.sh &
nm-applet &
$HOME/.config/polybar/launch.sh &
bspc config focus_follows_pointer true 
~/.config/berry/scripts/picom-toggle.sh &

setxkbmap -option caps:escape_shifted_capslock
xset r rate 300 50
chmod +x ~/scripts/*

source ~/.cache/wal/colors.sh &

bspc config active_border_color   $background
bspc config normal_border_color   $background
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color4
# auto start mpd
[ ! -s ~/.config/mpd/pid ] && mpd
