#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' '󰚌'
bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## 1 > terminal 
bspc rule -a Alacritty desktop='^1' follow=on focus=on
## 2 > web 
bspc rule -a firefox desktop='^2' follow=on focus=on
## 3 > file managers 
bspc rule -a ranger:ranger desktop='^3' follow=on focus=on
## 4 nvim
bspc rule -a nvim:nvim desktop='^4' follow=on focus=on
## 5 ghostwriter 
bspc rule -a ghostwriter desktop='^5' follow=on focus=on
wal -i ~/pix/wall.png &
setxkbmap -option caps:escape_shifted_capslock &
xset r rate 300 50 &
polybar &
picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
dunst &
~/.scripts/todo.sh
